/** \mainpage Driver Overview
  *
  * \section section_drv_info Driver Information
  * This Sensor Controller Interface driver has been generated by the Texas Instruments Sensor Controller
  * Studio tool:
  * - <b>Project name</b>:     HDC1080 sensor
  * - <b>Project file</b>:     D:/Projects/Sensor Controller Studio/HDC1080_sensor/hdc1080_sensor.scp
  * - <b>Code prefix</b>:      HDC1080
  * - <b>Operating system</b>: TI-RTOS
  * - <b>Tool version</b>:     2.7.0.155
  * - <b>Tool patches</b>:     None
  * - <b>Target chip</b>:      CC2640R2F, package QFN48 7x7 RGZ, revision -
  * - <b>Created</b>:          2020-12-15 12:50:34.725
  * - <b>Computer</b>:         NATAN-MAIN
  * - <b>User</b>:             Natan
  *
  * No user-provided resource definitions were used to generate this driver.
  *
  * No user-provided procedure definitions were used to generate this driver.
  *
  * Do not edit the generated source code files other than temporarily for debug purposes. Any
  * modifications will be overwritten by the Sensor Controller Studio when generating new output.
  *
  * \section section_drv_modules Driver Modules
  * The driver is divided into three modules:
  * - \ref module_scif_generic_interface, providing the API for:
  *     - Initializing and uninitializing the driver
  *     - Task control (for starting, stopping and executing Sensor Controller tasks)
  *     - Task data exchange (for producing input data to and consume output data from Sensor Controller
  *       tasks)
  * - \ref module_scif_driver_setup, containing:
  *     - The AUX RAM image (Sensor Controller code and data)
  *     - I/O mapping information
  *     - Task data structure information
  *     - Driver setup data, to be used in the driver initialization
  *     - Project-specific functionality
  * - \ref module_scif_osal, for flexible OS support:
  *     - Interfaces with the selected operating system
  *
  * It is possible to use output from multiple Sensor Controller Studio projects in one application. Only
  * one driver setup may be active at a time, but it is possible to switch between these setups. When
  * using this option, there is one instance of the \ref module_scif_generic_interface and
  * \ref module_scif_osal modules, and multiple instances of the \ref module_scif_driver_setup module.
  * This requires that:
  * - The outputs must be generated using the same version of Sensor Controller Studio
  * - The outputs must use the same operating system
  * - The outputs must use different source code prefixes (inserted into all globals of the
  *   \ref module_scif_driver_setup)
  *
  *
  * \section section_project_info Project Description
  * No description entered
  *
  *
  * \subsection section_io_mapping I/O Mapping
  * Task I/O functions are mapped to the following pins:
  * - TaskHDC1080:
  *     - <b>I2C SCL</b>: DIO4
  *     - <b>I2C SDA</b>: DIO5
  *
  *
  * \section section_task_info Task Description(s)
  * This driver supports the following task(s):
  *
  *
  * \subsection section_task_desc_task_hdc1080 TaskHDC1080
  * No description entered
  *
  */




/** \addtogroup module_scif_driver_setup Driver Setup
  *
  * \section section_driver_setup_overview Overview
  *
  * This driver setup instance has been generated for:
  * - <b>Project name</b>:     HDC1080 sensor
  * - <b>Code prefix</b>:      HDC1080
  *
  * The driver setup module contains the generated output from the Sensor Controller Studio project:
  * - Location of task control and scheduling data structures in AUX RAM
  * - The AUX RAM image, and the size the image
  * - Task data structure information (location, size and buffer count)
  * - I/O pin mapping translation table
  * - Task resource initialization and uninitialization functions
  * - Hooks for run-time logging
  *
  * @{
  */
#ifndef SCIF_HDC1080_H
#define SCIF_HDC1080_H

#include <stdint.h>
#include <stdbool.h>
#include "scif_framework.h"
#include "scif_osal_tirtos.h"


/// Target chip name
#define SCIF_HDC1080_TARGET_CHIP_NAME_CC2640R2F
/// Target chip package
#define SCIF_HDC1080_TARGET_CHIP_PACKAGE_QFN48_7X7_RGZ

/// Number of tasks implemented by this driver
#define SCIF_HDC1080_TASK_COUNT 1

/// TaskHDC1080: Task ID
#define SCIF_HDC1080_TASK_HDC1080_TASK_ID 0


/// TaskHDC1080: 
#define SCIF_HDC1080_TASK_HDC1080_ALS_I2C_ADDR 128
/// TaskHDC1080: HDC1080 configuration and status
#define SCIF_HDC1080_TASK_HDC1080_CONFIG_ADR 2
/// TaskHDC1080: Device ID
#define SCIF_HDC1080_TASK_HDC1080_DEV_ID_ADR 255
/// TaskHDC1080: 
#define SCIF_HDC1080_TASK_HDC1080_HUM_ADR 1
/// TaskHDC1080: Manufacturer ID
#define SCIF_HDC1080_TASK_HDC1080_MAN_ID_ADR 254
/// TaskHDC1080: Mode of acquisition bit
#define SCIF_HDC1080_TASK_HDC1080_MODE_MASK 4096
/// TaskHDC1080: First 2 bytes of the serial ID reg. address
#define SCIF_HDC1080_TASK_HDC1080_SER_ID_FIRST_ADR 251
/// TaskHDC1080: Last byte of the serial ID reg. address
#define SCIF_HDC1080_TASK_HDC1080_SER_ID_LAST_ADR 253
/// TaskHDC1080: Mid 2 bytes of the serial ID reg. address
#define SCIF_HDC1080_TASK_HDC1080_SER_ID_MID_ADR 252
/// TaskHDC1080: 
#define SCIF_HDC1080_TASK_HDC1080_TMP_ADR 0
/// TaskHDC1080 I/O mapping: I2C SCL
#define SCIF_HDC1080_TASK_HDC1080_DIO_I2C_SCL 4
/// TaskHDC1080 I/O mapping: I2C SDA
#define SCIF_HDC1080_TASK_HDC1080_DIO_I2C_SDA 5


// All shared data structures in AUX RAM need to be packed
#pragma pack(push, 2)


/// TaskHDC1080: Task configuration structure
typedef struct {
    uint16_t CfgReadEnable;     ///< Enable read HDC1080 configuration and status
    uint16_t CfgWriteEnable;    ///< Enable write HDC1080 configuration and status
    uint16_t DevIdEnable;       ///< 
    uint16_t HumEnable;         ///< 
    uint16_t ManIdEnable;       ///< 
    uint16_t MeasureBothEnable; ///< 
    uint16_t SerIdEnable;       ///< Enable Serial ID
    uint16_t TmpEnable;         ///< 
} SCIF_HDC1080_TASK_HDC1080_CFG_T;


/// TaskHDC1080: Task input data structure
typedef struct {
    uint16_t CfgData; ///< 
} SCIF_HDC1080_TASK_HDC1080_INPUT_T;


/// TaskHDC1080: Task output data structure
typedef struct {
    uint16_t ConfigValue; ///< Configuration register value
    uint16_t ErrFlag;     ///< 
    uint16_t SerIdFirst;  ///< First 2 bytes of the serial ID of the part
    uint16_t SerIdLast;   ///< Last byte bit of the serial ID of the part
    uint16_t SerIdMid;    ///< Mid 2 bytes of the serial ID of the part
    uint16_t devID;       ///< 
    uint16_t hum;         ///< 
    uint16_t manID;       ///< 
    int16_t  tmp;         ///< 
} SCIF_HDC1080_TASK_HDC1080_OUTPUT_T;


/// TaskHDC1080: Task state structure
typedef struct {
    uint16_t i2cStatus; ///< I2C master status
} SCIF_HDC1080_TASK_HDC1080_STATE_T;


/// Sensor Controller task data (configuration, input buffer(s), output buffer(s) and internal state)
typedef struct {
    struct {
        SCIF_HDC1080_TASK_HDC1080_CFG_T cfg;
        SCIF_HDC1080_TASK_HDC1080_INPUT_T input;
        SCIF_HDC1080_TASK_HDC1080_OUTPUT_T output;
        SCIF_HDC1080_TASK_HDC1080_STATE_T state;
    } taskHdc1080;
} SCIF_HDC1080_TASK_DATA_T;

/// Sensor Controller task generic control (located in AUX RAM)
#define scifHdc1080TaskData    (*((volatile SCIF_HDC1080_TASK_DATA_T*) 0x400E00EA))


// Initialized internal driver data, to be used in the call to \ref scifInit()
extern const SCIF_DATA_T scifHdc1080DriverSetup;


// Restore previous struct packing setting
#pragma pack(pop)


// AUX I/O re-initialization functions
void scifHdc1080ReinitTaskIo(uint32_t bvTaskIds);


// RTC-based tick generation control
void scifHdc1080StartRtcTicks(uint32_t tickStart, uint32_t tickPeriod);
void scifHdc1080StartRtcTicksNow(uint32_t tickPeriod);
void scifHdc1080StopRtcTicks(void);


#endif
//@}


// Generated by NATAN-MAIN at 2020-12-15 12:50:34.725
